### PR TITLE
Build and push Docker image on release tags

### PR DESCRIPTION
**Pull request by scop**
As discussed in https://github.com/Perl-Critic/Perl-Critic/issues/999.

Test workflow run in my fork for a test tag v0.000: https://github.com/scop/Perl-Critic/actions/runs/3817896051 (with "Perl-Critic" and "perl-critic" repo owner replaced by "scop" compared to this PR)

Result testable as `docker run --rm -it ghcr.io/scop/perl-critic:v0.000`

Compared to the top level `build.sh` in the current `docker` branch, this obviously uses GH actions all the way, but also more importantly builds a multiplatform image, with amd64 and arm64 in it.

### CODE REVIEW

**Comment by petdance** [comment]
I can pull it OK but I get no output.

```
$ docker run --rm -it ghcr.io/scop/perl-critic:v0.000 help
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
```

Is there something else I should be doing?

**Comment by petdance** [comment]
Any idea why this fails here on 5.10? It builds on 5.10 just fine. Is the dependency install trying to install too much?

**Comment by scop** [comment]
I've no experience with podman, but with "the" docker I get:
```
$ docker run --rm -it ghcr.io/scop/perl-critic:v0.000 help
No such file or directory: 'help'
[...followed by the perlcritic usage message...]
```

For some actual use one would likely do something like `docker run --rm -v /path/to/some/perl/code:/work:ro ghcr.io/scop/perl-critic:v0.000 /work`. Having actually tried that, it works otherwise but starts with this:
```
$ docker run --rm -v /usr/lib/x86_64-linux-gnu/perl-base:/work:ro ghcr.io/scop/perl-critic:v0.000 /work
Couldn't require Perl::Critic::Policy::Documentation::PodSpelling : Can't locate Pod/Spell.pm in @INC (you may need to install the Pod::Spell module) (@INC contains: /usr/local/lib/perl5/site_perl /usr/local/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl) at /usr/local/lib/perl5/site_perl/Perl/Critic/Policy/Documentation/PodSpelling.pm line 13.
BEGIN failed--compilation aborted at /usr/local/lib/perl5/site_perl/Perl/Critic/Policy/Documentation/PodSpelling.pm line 13.
Compilation failed in require at /usr/share/perl5/vendor_perl/Module/Runtime.pm line 314.
 at /usr/share/perl5/vendor_perl/Module/Pluggable.pm line 32.
/work/AutoLoader.pm: Stricture disabled at line 37, column 6.  See page 429 of PBP.  (Severity: 5)
[...rest of expected stuff...]
```
Seems we should add Pod::Spell in the image.

No idea about the 5.10, except that I believe it's unrelated. This workflow should run on tags only, and even then I suppose it wouldn't be run on any "outside" Perl in particular, but just building within the designated Alpine container.

**Comment by scop** [comment]
https://github.com/Perl-Critic/Perl-Critic/pull/1013 has the Pod::Spell fix.
